services:
  db:
    # image: postgres
    image: ankane/pgvector
    container_name: postgres_server
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # 👈 mount to local folder
