[project]
name = "mcp-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-mcp>=0.3.4",
    "fastmcp>=2.5.2",
    "nest-asyncio>=1.6.0",
]
